spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/bookdb
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret: ODQ0NzQwMzY5MjI1Mzk3YTZlYjAwY2ZhOTFhOTc0MDYzY2Q5Yzc4YzlmNjI1YjAwMDFlMjFlNzY0MmY5YTM2Mg==
logging:
  level:
    org.springframework.security: DEBUG
    com.mini4.Book.jwt: DEBUG
    com.mini4.Book.service: DEBUG
    com.mini4.Book.controller: DEBUG